-- ----------------------------------------------------------------------------
-- 美食分享平台 丰富演示数据（自动生成，请勿手工修改）
-- 内容：12 个分类 / 42 道美食（本地生成封面图）/ 12 位用户 / 点赞收藏评论
-- 说明：所有账号密码均为 admin123；脚本可重复执行
-- ----------------------------------------------------------------------------
SET NAMES utf8mb4;

-- 0、清理上一次生成的演示数据
DELETE FROM `food_comment`  WHERE `food_id` >= 200;
DELETE FROM `food_like`     WHERE `food_id` >= 200;
DELETE FROM `food_favorite` WHERE `food_id` >= 200;
DELETE FROM `food_info`     WHERE `id` >= 200;
-- 分类使用固定 ID，先删后插保证可重复执行
DELETE FROM `food_category` WHERE `id` BETWEEN 100 AND 111;

-- 1、演示用户（密码统一 admin123）
DELETE FROM `sys_user_role` WHERE `user_id` > 100;
DELETE FROM `sys_user` WHERE `user_id` > 100;
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (101, 103, 'chuancai', '川味小厨', '00', 'chuancai@zzyl.com', '13800000001', '0', '/profile/upload/seed/avatar_chuancai.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (102, 103, 'yuecai', '粤菜阿明', '00', 'yuecai@zzyl.com', '13800000002', '1', '/profile/upload/seed/avatar_yuecai.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (103, 103, 'lucai', '鲁味老张', '00', 'lucai@zzyl.com', '13800000003', '0', '/profile/upload/seed/avatar_lucai.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (104, 103, 'tianpin', '甜品少女', '00', 'tianpin@zzyl.com', '13800000004', '1', '/profile/upload/seed/avatar_tianpin.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (105, 103, 'xiaochi', '夜市大王', '00', 'xiaochi@zzyl.com', '13800000005', '0', '/profile/upload/seed/avatar_xiaochi.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (106, 103, 'xiangcai', '湘辣妹子', '00', 'xiangcai@zzyl.com', '13800000006', '1', '/profile/upload/seed/avatar_xiangcai.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (107, 103, 'jiachang', '妈妈的味道', '00', 'jiachang@zzyl.com', '13800000007', '0', '/profile/upload/seed/avatar_jiachang.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (108, 103, 'tangeng', '汤汤水水', '00', 'tangeng@zzyl.com', '13800000008', '1', '/profile/upload/seed/avatar_tangeng.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (109, 103, 'mianshi', '面点师傅', '00', 'mianshi@zzyl.com', '13800000009', '0', '/profile/upload/seed/avatar_mianshi.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (110, 103, 'yinpin', '奶茶控', '00', 'yinpin@zzyl.com', '13800000010', '1', '/profile/upload/seed/avatar_yinpin.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (111, 103, 'sushi', '轻食主义', '00', 'sushi@zzyl.com', '13800000011', '0', '/profile/upload/seed/avatar_sushi.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
INSERT INTO `sys_user` (`user_id`,`dept_id`,`user_name`,`nick_name`,`user_type`,`email`,`phonenumber`,`sex`,`avatar`,`password`,`status`,`del_flag`,`create_by`,`create_time`,`update_by`,`update_time`,`remark`) VALUES (112, 103, 'hongbei', '烤箱日记', '00', 'hongbei@zzyl.com', '13800000012', '1', '/profile/upload/seed/avatar_hongbei.jpg', '$2a$10$7JB720yubVSZvUI0rEqK/.VqGOZTH.ulu33dHOiBE8ByOhJIrdAu2', '0', '0', 'admin', sysdate(), '', NULL, '演示用户');
-- 演示用户统一授予普通用户角色（拥有 App 端菜单）
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (101, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (102, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (103, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (104, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (105, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (106, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (107, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (108, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (109, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (110, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (111, 2);
INSERT INTO `sys_user_role` (`user_id`,`role_id`) VALUES (112, 2);

-- 2、分类
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (100, '川菜', 1, '0', 'admin', sysdate(), '麻辣鲜香，一菜一格');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (101, '粤菜', 2, '0', 'admin', sysdate(), '清而不淡，鲜而不俗');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (102, '鲁菜', 3, '0', 'admin', sysdate(), '咸鲜为主，火候见长');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (103, '甜品', 4, '0', 'admin', sysdate(), '饭后一口，心情变甜');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (104, '小吃', 5, '0', 'admin', sysdate(), '街头巷尾的烟火气');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (105, '湘菜', 6, '0', 'admin', sysdate(), '香辣浓郁，无辣不欢');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (106, '家常菜', 7, '0', 'admin', sysdate(), '一日三餐，家的味道');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (107, '汤羹', 8, '0', 'admin', sysdate(), '一碗热汤，暖胃暖心');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (108, '面食', 9, '0', 'admin', sysdate(), '面香扑鼻，碳水快乐');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (109, '饮品', 10, '0', 'admin', sysdate(), '解腻解辣，随手一杯');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (110, '素食', 11, '0', 'admin', sysdate(), '清爽少负担');
INSERT INTO `food_category` (`id`,`name`,`order_num`,`status`,`create_by`,`create_time`,`remark`) VALUES (111, '烘焙', 12, '0', 'admin', sysdate(), '烤箱里的香气');

-- 3、美食（id 顺延 200 起，image 指向本地生成的封面）
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (200, 100, '麻婆豆腐', '/profile/upload/seed/dish_ad19ef128cd3.jpg', '麻辣鲜香，下饭神器', '豆腐嫩滑、牛肉臊子酥香，一勺红油盖住整碗米饭。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 128, 56, 0, '0', 'admin', date_sub(sysdate(), interval 20 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (201, 100, '宫保鸡丁', '/profile/upload/seed/dish_268ca7407944.jpg', '酸甜微辣，鸡肉嫩滑', '鸡丁滑嫩、花生酥脆，糖醋汁收得亮亮的。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 96, 40, 0, '0', 'admin', date_sub(sysdate(), interval 21 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (202, 100, '回锅肉', '/profile/upload/seed/dish_e4e758f6e2e2.jpg', '肥而不腻，川菜之首', '二刀肉先煮后炒，郫县豆瓣炒出红油，蒜苗一拌香气冲鼻。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 142, 61, 0, '0', 'chuancai', date_sub(sysdate(), interval 22 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (203, 100, '水煮鱼', '/profile/upload/seed/dish_b9f6aa0564e5.jpg', '麻辣鲜烫，鱼片嫩滑', '鱼片薄而不断，热油泼在花椒辣椒上的一瞬间最香。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 167, 72, 0, '0', 'chuancai', date_sub(sysdate(), interval 23 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (204, 100, '酸辣粉', '/profile/upload/seed/dish_a586a719a491.jpg', '酸辣开胃，红薯粉弹牙', '红薯粉煮到透亮，浇上酸辣汤底，撒酥花生和香菜。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 88, 33, 0, '0', 'chuancai', date_sub(sysdate(), interval 24 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (205, 101, '白切鸡', '/profile/upload/seed/dish_1487405eaab0.jpg', '皮爽肉滑，原汁原味', '走地鸡浸熟后过冰水，皮爽肉滑，蘸姜葱蓉最地道。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 85, 32, 0, '0', 'admin', date_sub(sysdate(), interval 25 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (206, 101, '虾饺', '/profile/upload/seed/dish_8810387b7b66.jpg', '皮薄透明，虾仁弹牙', '澄面皮擀得透光，包整只鲜虾，蒸六分钟即可。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 99, 44, 0, '0', 'yuecai', date_sub(sysdate(), interval 26 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (207, 101, '烧鹅', '/profile/upload/seed/dish_64c46d178d1e.jpg', '皮脆肉嫩，油光透亮', '黑鬃鹅腌足一晚，挂炉烤到皮脆，斩件淋原汁。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 121, 52, 0, '0', 'yuecai', date_sub(sysdate(), interval 27 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (208, 101, '艇仔粥', '/profile/upload/seed/dish_8d90b1664c01.jpg', '料足绵滑，一碗鲜甜', '米粒煮到开花，加鱼片、猪皮、花生、油条碎。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 64, 21, 0, '0', 'yuecai', date_sub(sysdate(), interval 28 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (209, 102, '红烧肉', '/profile/upload/seed/dish_eb89608f188e.jpg', '肥而不腻，入口即化', '五花肉炒糖色上色，小火焖到颤巍巍，收汁挂亮。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 150, 70, 0, '0', 'admin', date_sub(sysdate(), interval 29 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (210, 102, '糖醋鲤鱼', '/profile/upload/seed/dish_c213437d1ca2.jpg', '外酥里嫩，酸甜适口', '鲤鱼改花刀炸定型，糖醋汁一浇吱吱作响。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 107, 38, 0, '0', 'lucai', date_sub(sysdate(), interval 0 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (211, 102, '九转大肠', '/profile/upload/seed/dish_86268f3d4dbb.jpg', '五味俱全，越嚼越香', '大肠反复洗净煮透，酸甜香辣咸层层递进。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 76, 25, 0, '0', 'lucai', date_sub(sysdate(), interval 1 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (212, 103, '提拉米苏', '/profile/upload/seed/dish_31c87501d515.jpg', '咖啡与奶油的完美结合', '手指饼干浸足咖啡液，马斯卡彭层层叠起，冷藏一夜。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 200, 120, 0, '0', 'admin', date_sub(sysdate(), interval 2 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (213, 103, '芒果班戟', '/profile/upload/seed/dish_d4a78e1e17e8.jpg', '软糯饼皮裹满奶油', '班戟皮煎得薄而均匀，卷入芒果块与打发奶油。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 134, 58, 0, '0', 'tianpin', date_sub(sysdate(), interval 3 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (214, 103, '双皮奶', '/profile/upload/seed/dish_42eb62e2cff7.jpg', '奶香浓郁，滑如凝脂', '水牛奶煮出奶皮，蛋清回蒸成冻，冷热皆宜。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 118, 47, 0, '0', 'tianpin', date_sub(sysdate(), interval 4 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (215, 103, '杨枝甘露', '/profile/upload/seed/dish_591e2752bbd8.jpg', '芒果西柚，清甜微苦', '芒果打泥配西柚粒与西米，冰镇后风味最佳。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 156, 66, 0, '0', 'tianpin', date_sub(sysdate(), interval 5 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (216, 104, '小笼包', '/profile/upload/seed/dish_d1c97d8b6daf.jpg', '皮薄馅多，汤汁鲜美', '皮冻切碎拌进肉馅，蒸后一咬满口汤。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 180, 90, 0, '0', 'admin', date_sub(sysdate(), interval 6 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (217, 104, '生煎包', '/profile/upload/seed/dish_9ef8e85b142a.jpg', '底脆顶软，一咬爆汁', '平底锅先煎后焖，撒芝麻葱花，底部金黄酥脆。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 145, 55, 0, '0', 'xiaochi', date_sub(sysdate(), interval 7 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (218, 104, '煎饼果子', '/profile/upload/seed/dish_303ddcffab53.jpg', '现摊现卷，香脆管饱', '绿豆面糊摊薄，磕蛋刷酱，夹薄脆与生菜。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 97, 29, 0, '0', 'xiaochi', date_sub(sysdate(), interval 8 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (219, 104, '烤冷面', '/profile/upload/seed/dish_a94e5bf0b720.jpg', '酸甜微辣，夜市顶流', '冷面铁板煎软，刷蒜蓉辣酱，加蛋加肠。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 112, 36, 0, '0', 'xiaochi', date_sub(sysdate(), interval 9 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (220, 104, '冰糖葫芦', '/profile/upload/seed/dish_fb9fb0696c7d.jpg', '酸甜脆口，童年味道', '山楂去核穿串，熬糖到拉丝，裹匀后速冷。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 86, 24, 0, '0', 'xiaochi', date_sub(sysdate(), interval 10 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (221, 105, '剁椒鱼头', '/profile/upload/seed/dish_be5cd664c090.jpg', '鲜辣够味，鱼肉滑嫩', '胖头鱼头铺满剁椒，旺火蒸二十分钟，淋热油。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 163, 68, 0, '0', 'xiangcai', date_sub(sysdate(), interval 11 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (222, 105, '小炒黄牛肉', '/profile/upload/seed/dish_fa767e95b203.jpg', '香辣下饭，牛肉带劲', '黄牛肉逆纹切薄片，猛火快炒，小米椒提香。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 139, 49, 0, '0', 'xiangcai', date_sub(sysdate(), interval 12 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (223, 105, '辣椒炒肉', '/profile/upload/seed/dish_608caac3ab44.jpg', '湘菜灵魂，配饭一绝', '螺丝椒拍裂干煸，五花肉出油后再合炒。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 158, 63, 0, '0', 'xiangcai', date_sub(sysdate(), interval 13 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (224, 106, '西红柿炒鸡蛋', '/profile/upload/seed/dish_1b937ab56a83.jpg', '国民家常，酸甜适口', '番茄炒出沙，蛋液滑散回锅，一点点糖提鲜。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 176, 71, 0, '0', 'jiachang', date_sub(sysdate(), interval 14 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (225, 106, '青椒土豆丝', '/profile/upload/seed/dish_ab4ad87be45c.jpg', '爽脆酸香，快手小炒', '土豆切细丝泡水去淀粉，大火快炒保持脆感。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 102, 34, 0, '0', 'jiachang', date_sub(sysdate(), interval 15 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (226, 106, '清蒸鲈鱼', '/profile/upload/seed/dish_dfb180812517.jpg', '原味鲜嫩，蒸八分钟', '鲈鱼改刀摆盘，水开后蒸八分钟，淋豉油撒葱丝。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 128, 45, 0, '0', 'jiachang', date_sub(sysdate(), interval 16 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (227, 107, '番茄牛腩汤', '/profile/upload/seed/dish_ad9c098c1f15.jpg', '汤浓味厚，牛腩软烂', '牛腩焯水后与番茄同炖两小时，酸甜中带肉香。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 124, 48, 0, '0', 'tangeng', date_sub(sysdate(), interval 17 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (228, 107, '玉米排骨汤', '/profile/upload/seed/dish_d976bea23bf4.jpg', '清甜滋补，老少皆宜', '排骨焯净浮沫，加玉米胡萝卜慢炖，出锅前调味。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 98, 31, 0, '0', 'tangeng', date_sub(sysdate(), interval 18 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (229, 107, '银耳莲子羹', '/profile/upload/seed/dish_cc17c02da0cf.jpg', '胶质满满，润燥养颜', '银耳泡发撕小朵，加莲子红枣炖到出胶。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 87, 27, 0, '0', 'tangeng', date_sub(sysdate(), interval 19 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (230, 108, '兰州牛肉面', '/profile/upload/seed/dish_3d58e3f08e3d.jpg', '一清二白三红四绿', '牛骨清汤配手工拉面，萝卜片、辣油、香菜蒜苗齐全。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 171, 74, 0, '0', 'mianshi', date_sub(sysdate(), interval 20 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (231, 108, '炸酱面', '/profile/upload/seed/dish_b600e1527a62.jpg', '酱香浓郁，拌开喷香', '六必居干黄酱小火炸透，配黄瓜丝与手擀面。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 109, 35, 0, '0', 'mianshi', date_sub(sysdate(), interval 21 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (232, 108, '葱油拌面', '/profile/upload/seed/dish_fcf9c62f9945.jpg', '葱香入骨，简单极致', '小葱慢炸到焦香，葱油与酱油糖拌进热面。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 115, 39, 0, '0', 'mianshi', date_sub(sysdate(), interval 22 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (233, 109, '杨梅冰饮', '/profile/upload/seed/dish_dafffaed1511.jpg', '酸甜冰爽，夏天必备', '杨梅煮出汁水，加冰糖冷藏，喝前加冰块。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 93, 26, 0, '0', 'yinpin', date_sub(sysdate(), interval 23 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (234, 109, '柠檬蜂蜜茶', '/profile/upload/seed/dish_785444b2b427.jpg', '清新解腻，冷热皆宜', '柠檬盐洗切片，与蜂蜜分层腌渍三天。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 78, 22, 0, '0', 'yinpin', date_sub(sysdate(), interval 24 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (235, 109, '芋泥波波奶茶', '/profile/upload/seed/dish_e17bb52f807d.jpg', '芋香绵密，珍珠弹牙', '荔浦芋头蒸熟压泥，配红茶奶底与黑糖珍珠。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 147, 59, 0, '0', 'yinpin', date_sub(sysdate(), interval 25 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (236, 110, '凉拌黄瓜', '/profile/upload/seed/dish_4c0b46d9daee.jpg', '清脆爽口，两分钟上桌', '黄瓜拍裂更入味，蒜末、香醋、辣椒油拌匀。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 84, 23, 0, '0', 'sushi', date_sub(sysdate(), interval 26 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (237, 110, '干煸四季豆', '/profile/upload/seed/dish_59f6bde3622e.jpg', '外皱里嫩，咸香微辣', '四季豆煸到起皱，肉末与芽菜炒香后合炒。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 91, 28, 0, '0', 'sushi', date_sub(sysdate(), interval 27 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (238, 110, '西红柿疙瘩汤', '/profile/upload/seed/dish_6c418f366ac6.jpg', '暖胃舒服，做法简单', '面疙瘩搓小粒下锅，番茄打底煮出浓汤。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 72, 19, 0, '0', 'sushi', date_sub(sysdate(), interval 28 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (239, 111, '戚风蛋糕', '/profile/upload/seed/dish_2d6cfb54810b.jpg', '松软细腻，入口即化', '蛋白打到湿性发泡，低温慢烤后倒扣晾凉。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 138, 57, 0, '0', 'hongbei', date_sub(sysdate(), interval 29 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (240, 111, '黄油曲奇', '/profile/upload/seed/dish_8da5331a7ab5.jpg', '酥到掉渣，奶香十足', '黄油打发到发白，筛入低粉挤花，烤箱定型。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 106, 37, 0, '0', 'hongbei', date_sub(sysdate(), interval 0 day), '');
INSERT INTO `food_info` (`id`,`category_id`,`title`,`image`,`description`,`content`,`like_count`,`favorite_count`,`comment_count`,`status`,`create_by`,`create_time`,`remark`) VALUES (241, 111, '全麦贝果', '/profile/upload/seed/dish_906288fa0ef1.jpg', '外韧内软，越嚼越香', '面团先煮后烤，表皮紧实，夹乳酪最搭。\n\n小贴士：食材提前备齐，火候宁小勿大，出锅前再调味。', 81, 26, 0, '0', 'hongbei', date_sub(sysdate(), interval 1 day), '');

INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1000, 200, 110, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1001, 200, 105, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1002, 201, 109, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1003, 201, 106, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1004, 201, 110, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1005, 201, 105, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1006, 201, 108, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1007, 202, 111, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1008, 202, 108, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1009, 203, 110, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1010, 203, 112, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1011, 203, 103, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1012, 203, 105, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1013, 204, 104, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1014, 204, 110, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1015, 204, 103, date_sub(sysdate(), interval 20 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1016, 204, 105, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1017, 205, 107, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1018, 205, 104, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1019, 205, 105, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1020, 205, 111, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1021, 206, 103, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1022, 206, 105, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1023, 206, 104, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1024, 206, 110, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1025, 206, 109, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1026, 206, 106, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1027, 207, 103, date_sub(sysdate(), interval 22 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1028, 207, 106, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1029, 207, 104, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1030, 207, 102, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1031, 207, 112, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1032, 207, 105, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1033, 207, 101, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1034, 207, 111, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1035, 208, 101, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1036, 208, 112, date_sub(sysdate(), interval 20 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1037, 208, 110, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1038, 208, 109, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1039, 208, 111, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1040, 208, 105, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1041, 208, 107, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1042, 208, 104, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1043, 208, 102, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1044, 208, 106, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1045, 209, 108, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1046, 209, 101, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1047, 209, 109, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1048, 209, 110, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1049, 209, 103, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1050, 210, 111, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1051, 210, 109, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1052, 210, 107, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1053, 210, 108, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1054, 210, 106, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1055, 210, 102, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1056, 210, 101, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1057, 210, 105, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1058, 210, 110, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1059, 211, 106, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1060, 211, 110, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1061, 211, 103, date_sub(sysdate(), interval 21 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1062, 211, 112, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1063, 211, 104, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1064, 212, 112, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1065, 212, 105, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1066, 212, 108, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1067, 212, 107, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1068, 212, 103, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1069, 212, 106, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1070, 212, 111, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1071, 212, 104, date_sub(sysdate(), interval 21 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1072, 213, 102, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1073, 213, 110, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1074, 213, 104, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1075, 213, 101, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1076, 213, 108, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1077, 213, 112, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1078, 213, 105, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1079, 214, 103, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1080, 214, 108, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1081, 214, 106, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1082, 215, 105, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1083, 215, 101, date_sub(sysdate(), interval 22 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1084, 215, 102, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1085, 215, 104, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1086, 215, 103, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1087, 215, 110, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1088, 215, 108, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1089, 215, 109, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1090, 215, 107, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1091, 216, 109, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1092, 216, 108, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1093, 216, 102, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1094, 217, 101, date_sub(sysdate(), interval 20 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1095, 217, 110, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1096, 217, 105, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1097, 217, 107, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1098, 217, 109, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1099, 217, 111, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1100, 217, 104, date_sub(sysdate(), interval 21 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1101, 217, 103, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1102, 217, 102, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1103, 218, 107, date_sub(sysdate(), interval 22 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1104, 218, 104, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1105, 218, 106, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1106, 218, 110, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1107, 218, 101, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1108, 218, 103, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1109, 219, 108, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1110, 219, 101, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1111, 220, 107, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1112, 220, 105, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1113, 220, 111, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1114, 221, 111, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1115, 221, 107, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1116, 222, 110, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1117, 222, 101, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1118, 222, 104, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1119, 222, 107, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1120, 222, 112, date_sub(sysdate(), interval 22 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1121, 223, 101, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1122, 223, 109, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1123, 223, 106, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1124, 223, 107, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1125, 223, 102, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1126, 223, 105, date_sub(sysdate(), interval 22 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1127, 223, 110, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1128, 223, 112, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1129, 223, 103, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1130, 223, 108, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1131, 224, 107, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1132, 224, 104, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1133, 224, 112, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1134, 224, 102, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1135, 224, 110, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1136, 224, 106, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1137, 224, 108, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1138, 224, 105, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1139, 224, 103, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1140, 225, 110, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1141, 225, 102, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1142, 225, 106, date_sub(sysdate(), interval 20 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1143, 225, 105, date_sub(sysdate(), interval 22 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1144, 225, 101, date_sub(sysdate(), interval 22 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1145, 225, 111, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1146, 225, 107, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1147, 225, 103, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1148, 226, 105, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1149, 226, 112, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1150, 226, 107, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1151, 226, 109, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1152, 226, 101, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1153, 226, 108, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1154, 226, 104, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1155, 226, 106, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1156, 226, 111, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1157, 227, 111, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1158, 227, 110, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1159, 227, 107, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1160, 227, 104, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1161, 228, 105, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1162, 228, 111, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1163, 228, 107, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1164, 228, 104, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1165, 229, 107, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1166, 229, 108, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1167, 229, 104, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1168, 229, 110, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1169, 229, 101, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1170, 229, 111, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1171, 230, 108, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1172, 230, 109, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1173, 230, 103, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1174, 230, 106, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1175, 230, 111, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1176, 230, 101, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1177, 230, 104, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1178, 230, 107, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1179, 230, 112, date_sub(sysdate(), interval 20 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1180, 231, 108, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1181, 231, 107, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1182, 231, 105, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1183, 231, 111, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1184, 231, 112, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1185, 231, 110, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1186, 231, 101, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1187, 231, 102, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1188, 232, 103, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1189, 232, 108, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1190, 232, 109, date_sub(sysdate(), interval 20 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1191, 232, 110, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1192, 232, 101, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1193, 232, 106, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1194, 232, 107, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1195, 232, 105, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1196, 233, 104, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1197, 233, 106, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1198, 234, 111, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1199, 234, 112, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1200, 234, 104, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1201, 235, 103, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1202, 235, 109, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1203, 235, 106, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1204, 235, 111, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1205, 235, 104, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1206, 236, 111, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1207, 236, 112, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1208, 237, 103, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1209, 237, 106, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1210, 237, 105, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1211, 238, 102, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1212, 238, 104, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1213, 238, 106, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1214, 238, 110, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1215, 238, 105, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1216, 238, 107, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1217, 239, 111, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1218, 239, 101, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1219, 239, 104, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1220, 240, 106, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1221, 240, 107, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1222, 240, 108, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1223, 240, 102, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1224, 240, 111, date_sub(sysdate(), interval 24 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1225, 240, 105, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1226, 240, 101, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1227, 240, 104, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1228, 241, 110, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1229, 241, 108, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1230, 241, 105, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1231, 241, 102, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1232, 241, 104, date_sub(sysdate(), interval 23 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1233, 241, 101, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_like` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1234, 241, 111, date_sub(sysdate(), interval 2 day));

-- 5、收藏记录
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1500, 200, 104, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1501, 201, 103, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1502, 201, 101, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1503, 201, 112, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1504, 201, 104, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1505, 202, 112, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1506, 202, 109, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1507, 203, 101, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1508, 203, 103, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1509, 203, 106, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1510, 204, 102, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1511, 204, 107, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1512, 204, 106, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1513, 205, 103, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1514, 205, 107, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1515, 205, 104, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1516, 206, 110, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1517, 206, 106, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1518, 206, 105, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1519, 206, 112, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1520, 207, 104, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1521, 207, 101, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1522, 208, 109, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1523, 208, 106, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1524, 208, 105, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1525, 209, 108, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1526, 209, 105, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1527, 210, 108, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1528, 211, 105, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1529, 212, 110, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1530, 212, 106, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1531, 212, 108, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1532, 213, 103, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1533, 213, 105, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1534, 213, 109, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1535, 214, 105, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1536, 215, 101, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1537, 215, 106, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1538, 215, 108, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1539, 216, 107, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1540, 217, 102, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1541, 217, 105, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1542, 217, 111, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1543, 218, 110, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1544, 218, 107, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1545, 218, 111, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1546, 219, 101, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1547, 219, 110, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1548, 220, 109, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1549, 221, 101, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1550, 221, 111, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1551, 221, 106, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1552, 221, 110, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1553, 222, 110, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1554, 222, 106, date_sub(sysdate(), interval 4 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1555, 222, 104, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1556, 222, 102, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1557, 223, 111, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1558, 223, 103, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1559, 223, 110, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1560, 223, 108, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1561, 224, 110, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1562, 225, 103, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1563, 225, 101, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1564, 226, 109, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1565, 226, 108, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1566, 227, 112, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1567, 227, 106, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1568, 227, 105, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1569, 227, 102, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1570, 228, 109, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1571, 228, 103, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1572, 228, 107, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1573, 228, 104, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1574, 229, 108, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1575, 229, 102, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1576, 229, 112, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1577, 229, 105, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1578, 230, 107, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1579, 230, 106, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1580, 230, 103, date_sub(sysdate(), interval 3 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1581, 230, 102, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1582, 231, 110, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1583, 231, 106, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1584, 232, 112, date_sub(sysdate(), interval 10 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1585, 232, 105, date_sub(sysdate(), interval 13 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1586, 232, 109, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1587, 232, 107, date_sub(sysdate(), interval 19 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1588, 233, 106, date_sub(sysdate(), interval 1 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1589, 233, 104, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1590, 233, 107, date_sub(sysdate(), interval 17 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1591, 234, 112, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1592, 234, 102, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1593, 234, 107, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1594, 234, 111, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1595, 235, 107, date_sub(sysdate(), interval 7 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1596, 235, 110, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1597, 235, 108, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1598, 236, 112, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1599, 236, 107, date_sub(sysdate(), interval 9 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1600, 236, 106, date_sub(sysdate(), interval 11 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1601, 236, 105, date_sub(sysdate(), interval 16 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1602, 237, 112, date_sub(sysdate(), interval 2 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1603, 237, 106, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1604, 237, 110, date_sub(sysdate(), interval 18 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1605, 237, 111, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1606, 238, 104, date_sub(sysdate(), interval 14 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1607, 239, 108, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1608, 239, 106, date_sub(sysdate(), interval 15 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1609, 239, 112, date_sub(sysdate(), interval 8 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1610, 240, 109, date_sub(sysdate(), interval 12 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1611, 240, 106, date_sub(sysdate(), interval 6 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1612, 240, 104, date_sub(sysdate(), interval 0 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1613, 240, 110, date_sub(sysdate(), interval 5 day));
INSERT INTO `food_favorite` (`id`,`food_id`,`user_id`,`create_time`) VALUES (1614, 241, 108, date_sub(sysdate(), interval 3 day));

-- 6、评论（由不同用户发表，保证内容不是一个人发的）
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2000, 200, 110, '看着就香，明天就做！', 0, 1, '0', 'yinpin', date_sub(sysdate(), interval 14 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2001, 201, 111, '看起来简单，做起来也顺手。', 0, 0, '0', 'sushi', date_sub(sysdate(), interval 12 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2002, 202, 109, '看着就香，明天就做！', 0, 1, '0', 'mianshi', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2003, 202, 110, '我们那边也这么做，味道很亲切。', 0, 2, '0', 'yinpin', date_sub(sysdate(), interval 7 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2004, 203, 102, '孩子一口气吃了两碗。', 0, 5, '0', 'yuecai', date_sub(sysdate(), interval 8 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2005, 203, 112, '这个做法很地道，学到了。', 0, 1, '0', 'hongbei', date_sub(sysdate(), interval 4 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2006, 204, 102, '第一次做就成功了，谢谢分享。', 0, 0, '0', 'yuecai', date_sub(sysdate(), interval 11 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2007, 204, 105, '就是我想找的做法。', 0, 3, '0', 'xiaochi', date_sub(sysdate(), interval 2 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2008, 204, 107, '看着就香，明天就做！', 0, 2, '0', 'jiachang', date_sub(sysdate(), interval 12 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2009, 206, 105, '这个搭配没想到，很有意思。', 0, 2, '0', 'xiaochi', date_sub(sysdate(), interval 14 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2010, 206, 104, '配上米饭绝了。', 0, 4, '0', 'tianpin', date_sub(sysdate(), interval 16 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2011, 206, 110, '就是我想找的做法。', 0, 3, '0', 'yinpin', date_sub(sysdate(), interval 4 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2012, 208, 112, '我们那边也这么做，味道很亲切。', 0, 1, '0', 'hongbei', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2013, 208, 101, '按方子做了一次，家人都说好吃。', 0, 4, '0', 'chuancai', date_sub(sysdate(), interval 3 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2014, 209, 101, '周末就安排上。', 0, 4, '0', 'chuancai', date_sub(sysdate(), interval 2 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2015, 211, 104, '第一次做就成功了，谢谢分享。', 0, 4, '0', 'tianpin', date_sub(sysdate(), interval 14 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2016, 211, 103, '材料家里都有，太方便了。', 0, 4, '0', 'lucai', date_sub(sysdate(), interval 3 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2017, 211, 102, '这个做法很地道，学到了。', 0, 3, '0', 'yuecai', date_sub(sysdate(), interval 11 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2018, 212, 105, '周末就安排上。', 0, 2, '0', 'xiaochi', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2019, 212, 111, '就是我想找的做法。', 0, 4, '0', 'sushi', date_sub(sysdate(), interval 1 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2020, 213, 112, '比外面卖的好吃多了。', 0, 2, '0', 'hongbei', date_sub(sysdate(), interval 5 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2021, 214, 110, '色泽太漂亮了，收藏了。', 0, 2, '0', 'yinpin', date_sub(sysdate(), interval 15 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2022, 214, 104, '材料家里都有，太方便了。', 0, 0, '0', 'tianpin', date_sub(sysdate(), interval 14 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2023, 214, 102, '我们那边也这么做，味道很亲切。', 0, 5, '0', 'yuecai', date_sub(sysdate(), interval 0 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2024, 215, 109, '比外面卖的好吃多了。', 0, 1, '0', 'mianshi', date_sub(sysdate(), interval 18 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2025, 216, 101, '按方子做了一次，家人都说好吃。', 0, 2, '0', 'chuancai', date_sub(sysdate(), interval 5 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2026, 216, 106, '按方子做了一次，家人都说好吃。', 0, 4, '0', 'xiangcai', date_sub(sysdate(), interval 18 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2027, 217, 104, '关键步骤讲得很清楚，赞。', 0, 5, '0', 'tianpin', date_sub(sysdate(), interval 7 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2028, 217, 103, '火候这一点太重要了。', 0, 2, '0', 'lucai', date_sub(sysdate(), interval 6 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2029, 218, 112, '已经做第二遍了，百吃不厌。', 0, 1, '0', 'hongbei', date_sub(sysdate(), interval 18 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2030, 218, 103, '周末就安排上。', 0, 2, '0', 'lucai', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2031, 218, 106, '比外面卖的好吃多了。', 0, 1, '0', 'xiangcai', date_sub(sysdate(), interval 6 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2032, 219, 104, '我们那边也这么做，味道很亲切。', 0, 1, '0', 'tianpin', date_sub(sysdate(), interval 17 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2033, 220, 108, '按方子做了一次，家人都说好吃。', 0, 5, '0', 'tangeng', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2034, 220, 107, '看起来简单，做起来也顺手。', 0, 3, '0', 'jiachang', date_sub(sysdate(), interval 17 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2035, 220, 103, '比外面卖的好吃多了。', 0, 5, '0', 'lucai', date_sub(sysdate(), interval 3 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2036, 221, 110, '就是我想找的做法。', 0, 0, '0', 'yinpin', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2037, 222, 101, '这个做法很地道，学到了。', 0, 1, '0', 'chuancai', date_sub(sysdate(), interval 7 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2038, 222, 102, '这个做法很地道，学到了。', 0, 0, '0', 'yuecai', date_sub(sysdate(), interval 16 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2039, 224, 107, '新手也能学会，感谢。', 0, 0, '0', 'jiachang', date_sub(sysdate(), interval 13 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2040, 225, 105, '看起来简单，做起来也顺手。', 0, 5, '0', 'xiaochi', date_sub(sysdate(), interval 7 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2041, 225, 108, '按方子做了一次，家人都说好吃。', 0, 3, '0', 'tangeng', date_sub(sysdate(), interval 16 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2042, 226, 111, '看着就香，明天就做！', 0, 2, '0', 'sushi', date_sub(sysdate(), interval 9 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2043, 226, 106, '已经做第二遍了，百吃不厌。', 0, 4, '0', 'xiangcai', date_sub(sysdate(), interval 13 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2044, 228, 105, '关键步骤讲得很清楚，赞。', 0, 1, '0', 'xiaochi', date_sub(sysdate(), interval 5 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2045, 228, 109, '新手也能学会，感谢。', 0, 2, '0', 'mianshi', date_sub(sysdate(), interval 3 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2046, 230, 112, '这个做法很地道，学到了。', 0, 4, '0', 'hongbei', date_sub(sysdate(), interval 8 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2047, 230, 103, '按方子做了一次，家人都说好吃。', 0, 4, '0', 'lucai', date_sub(sysdate(), interval 13 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2048, 230, 110, '按方子做了一次，家人都说好吃。', 0, 5, '0', 'yinpin', date_sub(sysdate(), interval 0 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2049, 231, 103, '火候这一点太重要了。', 0, 3, '0', 'lucai', date_sub(sysdate(), interval 1 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2050, 232, 110, '按方子做了一次，家人都说好吃。', 0, 0, '0', 'yinpin', date_sub(sysdate(), interval 7 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2051, 232, 108, '第一次做就成功了，谢谢分享。', 0, 3, '0', 'tangeng', date_sub(sysdate(), interval 13 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2052, 232, 105, '按方子做了一次，家人都说好吃。', 0, 1, '0', 'xiaochi', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2053, 235, 102, '就是我想找的做法。', 0, 4, '0', 'yuecai', date_sub(sysdate(), interval 7 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2054, 235, 108, '材料家里都有，太方便了。', 0, 0, '0', 'tangeng', date_sub(sysdate(), interval 5 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2055, 237, 104, '材料家里都有，太方便了。', 0, 0, '0', 'tianpin', date_sub(sysdate(), interval 15 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2056, 237, 110, '配上米饭绝了。', 0, 4, '0', 'yinpin', date_sub(sysdate(), interval 10 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2057, 237, 112, '关键步骤讲得很清楚，赞。', 0, 5, '0', 'hongbei', date_sub(sysdate(), interval 1 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2058, 238, 112, '看起来简单，做起来也顺手。', 0, 0, '0', 'hongbei', date_sub(sysdate(), interval 0 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2059, 238, 103, '孩子一口气吃了两碗。', 0, 3, '0', 'lucai', date_sub(sysdate(), interval 15 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2060, 239, 110, '周末就安排上。', 0, 5, '0', 'yinpin', date_sub(sysdate(), interval 4 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2061, 239, 102, '这个搭配没想到，很有意思。', 0, 4, '0', 'yuecai', date_sub(sysdate(), interval 19 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2062, 239, 101, '材料家里都有，太方便了。', 0, 3, '0', 'chuancai', date_sub(sysdate(), interval 1 day));
INSERT INTO `food_comment` (`id`,`food_id`,`user_id`,`content`,`parent_id`,`like_count`,`status`,`create_by`,`create_time`) VALUES (2063, 240, 111, '第一次做就成功了，谢谢分享。', 0, 3, '0', 'sushi', date_sub(sysdate(), interval 5 day));

-- 7、为原有示例内容补齐封面（本地生成的同款封面）
UPDATE `food_info` SET `image` = '/profile/upload/seed/dish_ad19ef128cd3.jpg', `create_by` = 'admin' WHERE `id` = 100;
UPDATE `food_info` SET `image` = '/profile/upload/seed/dish_268ca7407944.jpg', `create_by` = 'admin' WHERE `id` = 101;
UPDATE `food_info` SET `image` = '/profile/upload/seed/dish_1487405eaab0.jpg', `create_by` = 'admin' WHERE `id` = 102;
UPDATE `food_info` SET `image` = '/profile/upload/seed/dish_eb89608f188e.jpg', `create_by` = 'admin' WHERE `id` = 103;
UPDATE `food_info` SET `image` = '/profile/upload/seed/dish_31c87501d515.jpg', `create_by` = 'admin' WHERE `id` = 104;
UPDATE `food_info` SET `image` = '/profile/upload/seed/dish_d1c97d8b6daf.jpg', `create_by` = 'admin' WHERE `id` = 105;
UPDATE `food_info` SET `image` = '/profile/upload/seed/dish_548da55947dd.jpg', `create_by` = 'admin' WHERE `id` = 111;

-- 8、计数与明细保持一致
UPDATE `food_info` fi SET
  fi.`like_count`     = (SELECT COUNT(1) FROM `food_like`     fl WHERE fl.`food_id` = fi.`id`),
  fi.`favorite_count` = (SELECT COUNT(1) FROM `food_favorite` ff WHERE ff.`food_id` = fi.`id`),
  fi.`comment_count`  = (SELECT COUNT(1) FROM `food_comment`  fc WHERE fc.`food_id` = fi.`id`);

-- 9、校验
SELECT '分类数' AS `检查项`, COUNT(1) AS `结果` FROM `food_category`
UNION ALL SELECT '美食数', COUNT(1) FROM `food_info`
UNION ALL SELECT '演示用户数', COUNT(1) FROM `sys_user` WHERE `user_id` > 100
UNION ALL SELECT '发布者数量', COUNT(DISTINCT `create_by`) FROM `food_info`
UNION ALL SELECT '点赞数', COUNT(1) FROM `food_like`
UNION ALL SELECT '收藏数', COUNT(1) FROM `food_favorite`
UNION ALL SELECT '评论数', COUNT(1) FROM `food_comment`
UNION ALL SELECT '无封面美食', COUNT(1) FROM `food_info` WHERE `image` = '' OR `image` IS NULL;
